import { SessionProvider } from "@/components/SessionProvider";
import "tailwindcss/tailwind.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Login from "@/components/Login";
import NavBar from "./NavBar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="bg-gray-700">
        <SessionProvider session={session}>
          {!session ? <Login /> : 
            <div>
              {/* @ts-expect-error Server Component */}
              <NavBar />
              {children}
            </div>
          }
        </SessionProvider>
      </body>
    </html>
  );
}
